app:
  main:
    host: 0.0.0.0
    port: 8080
  directory:
    model_path: persistant/w2v/model_hh_fasttext
    stop_words_path: persistant/stopwords.txt
  url:
    sberautogetcars: https://api.sberauto.com/searcher/getCars
    autoru: https://auto.ru/-/ajax/desktop/searchlineSuggest/
  token: ad7f8ba8-000b-11ec-9a03-0242ac130003